### ISSUE TITLE
Add CoinBlockerList

### ISSUE THREAD

**Issue by ZeroDot1** [pyamsoft/update-hosts#3]
Please add the list CoinBlockerList.
https://github.com/ZeroDot1/CoinBlockerLists
Simple list that can help prevent cryptomining in the browser or other applications.
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts

**Comment by pyamsoft** [comment]
I have updated the script to source from the hosts file linked in your repository. Please let me know if this is satisfactory.

**Comment by ZeroDot1** [comment]
Thank you for adding the list, very good:)

**Comment by ZeroDot1** [comment]
![bildschirmfoto_2017-10-24_22-46-15](https://user-images.githubusercontent.com/28985171/31967130-42dd26be-b90d-11e7-96e2-8af4c4dfb25b.png)
