### ISSUE TITLE
Unbreak whitelist

### ISSUE THREAD

**Issue by dimqua** [pyamsoft/update-hosts#4]
How can I update [uBO Unbreak list](https://github.com/pyamsoft/update-hosts/blob/master/update-hosts#L1715) in the script to the [latest](https://github.com/uBlockOrigin/uAssets/blob/master/filters/unbreak.txt) version?

**Comment by pyamsoft** [comment]
There is a section in the code which has a "best attempt" at copying the unbreak list. You can add the new entries to this section by using regex syntax.

As an aside, the whitelist is a best effort, not an exact copy of the unbreak list. I will update it when I have the time to the best of my ability.

**Comment by dimqua** [comment]
Which regex should I add to copy **all** domains from uBO Unbreak list to the whitelist?

**Comment by pyamsoft** [comment]
There is unfortunately no simple regex at this moment to copy all domains from the unbreak list, one has to go through the list, figure out which entries can be converted into a simple host name format that host files can handle, and add it to the list.
