### ISSUE TITLE
Different tracking lists

### ISSUE THREAD

**Issue by ZeroDot1** [pyamsoft/update-hosts#5]
https://github.com/CHEF-KOCH/NSABlocklist/tree/master/Trackers
I think it's a good idea to add these lists.

**Comment by pyamsoft** [comment]
What do these lists block? What does the current list of sources not block that these do?

**Comment by ZeroDot1** [comment]
@pyamsoft This list blocks different tracking methods, which means that when you use these lists you can no longer track users on the Internet, for example to display personalized advertising.

**Comment by pyamsoft** [comment]
I see that it is specifically tailored to block NSA related sites.

I may add it to the project, but probably as an additional source instead of as a default one since the README claims the hosts file may break some sites.

Thank you for your contribution to the project
